riccardo = User.create(name: "Riccardo")
diogo = User.create(name: "Diogo")
manon = User.create(name: "Manon")
john = User.create(name: "John")
claire = User.create(name: "Claire")
sheila = User.create(name: "Sheila")
jack = User.create(name: "Jack")
pete = User.create(name: "Pete")

f1 = Friendship.create(user: riccardo, friend_id: diogo.id)
f2 = Friendship.create(user: diogo, friend_id: pete.id)
f3 = Friendship.create(user: riccardo, friend_id: manon.id)
f4 = Friendship.create(user: sheila, friend_id: riccardo.id)
f5 = Friendship.create(user: sheila, friend_id: diogo.id)
f6 = Friendship.create(user: claire, friend_id: sheila.id)
f7 = Friendship.create(user: riccardo, friend_id: john.id)

starwars = Movie.create(title: "Star Wars", release_year: 1977, global_rating: 9)
et = Movie.create(title: "E.T.", release_year: 1982, global_rating: 9.1)
roma = Movie.create(title: "Roma", release_year: 2018, global_rating: 9.6)
birdman = Movie.create(title: "Birdman", release_year: 2014, global_rating: 8.8)
veronicamars = Movie.create(title: "Veronica Mars", release_year: 2014, global_rating: 6.2)
mammamia = Movie.create(title: "Mamma Mia!", release_year: 2008, global_rating: 5.1)
greenbook = Movie.create(title: "Green Book", release_year: 2018, global_rating: 6.9)
network = Movie.create(title: "Network", release_year: 1976, global_rating: 8.8)
thebigshort = Movie.create(title: "The Big Short", release_year: 2015, global_rating: 8.1)

riccardo.review_movie(starwars, 5, "what a classic!")
diogo.review_movie(veronicamars, 5, "marshmallows rejoice, she is BACK")
diogo.review_movie(roma, 1, "why is this shit in black and white in 2018")
riccardo.review_movie(et, 4, "cute but it's kinda aged")
diogo.review_movie(network, 4, "a bit slow but so relevant 40 years later!")
riccardo.review_movie(veronicamars, 2, "BOOOOORING")
sheila.review_movie(veronicamars, 4, "expected better from my bestie Kristen Bell")
pete.review_movie(veronicamars, 5)