riccardo = User.create(name: "Riccardo")
diogo = User.create(name: "Diogo")
manon = User.create(name: "Manon")
john = User.create(name: "John")
claire = User.create(name: "Claire")
sheila = User.create(name: "Sheila")
jack = User.create(name: "Jack")
pete = User.create(name: "Pete")

f1 = Friendship.create(user: riccardo, friend_id: diogo.id)
f2 = Friendship.create(user: diogo, friend_id: pete.id)
f3 = Friendship.create(user: riccardo, friend_id: manon.id)
f4 = Friendship.create(user: sheila, friend_id: riccardo.id)
f5 = Friendship.create(user: sheila, friend_id: diogo.id)
f6 = Friendship.create(user: claire, friend_id: sheila.id)
f7 = Friendship.create(user: riccardo, friend_id: john.id)
